---
- name: service | Configuring Nautobot Service
  ansible.builtin.template:
    dest: /etc/systemd/system/nautobot.service
    src: nautobot.service.j2
    mode: u=rw,g=r,o=r
  become: true
  notify: restart nautobot

- name: service | Configuring Nautobot Worker Service
  ansible.builtin.template:
    dest: /etc/systemd/system/nautobot-worker.service
    src: nautobot-worker.service.j2
    mode: u=rw,g=r,o=r
  become: true
  notify: restart nautobot-worker
